# @package _group_
data_root_dir: /mnt/e/data/celeba_size/celeba-256
out_root_dir: /mnt/d/aResearch/repos/lama/experiments
tb_dir: /mnt/d/aResearch/repos/lama/tb_logs
pretrained_models: /mnt/d/aResearch/repos/lama
